WebsiteNoiThat/WebsiteNoiThat/Areas/Admin/Controllers/ProductCateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models.DAO;
using Models.EF;
using System.Web.Script.Serialization;
using PagedList;
using PagedList.Mvc;
using System.IO;
using WebsiteNoiThat.Common;

namespace WebsiteNoiThat.Areas.Admin.Controllers
{
    public class ProductCateController : HomeController
    {
        DBNoiThat db = new DBNoiThat();

        public ActionResult Index()
        {
            return View();
        }

        [HasCredential(RoleId = "VIEW_CATE")]
        public ActionResult Show()
        {
            var session = (UserLogin)Session[WebsiteNoiThat.Common.Commoncontent.user_sesion_admin];
            ViewBag.username = session.Username;

            return View(db.Categories.ToList());
        }

        [HttpGet]
        [HasCredential(RoleId = "ADD_CATE")]
        public ActionResult Add()
        {
            var session = (UserLogin)Session[WebsiteNoiThat.Common.Commoncontent.user_sesion_admin];
            ViewBag.username = session.Username;
            return View();
        }

        [HttpPost]
        [HasCredential(RoleId = "ADD_CATE")]
        public ActionResult Add(Category n)
        {
            var model = db.Categories.SingleOrDefault(a => a.CategoryId == n.CategoryId);
            if (model != null)
            {
                ModelState.AddModelError("CateError", "CategoryId already in use");
                return View();
            }
            else
            {
                db.Categories.Add(n);
                db.SaveChanges();
                return RedirectToAction("Show");
            }

        }

        [HttpGet]
        [HasCredential(RoleId = "EDIT_CATE")]
        public ActionResult Edit(int CategoryId)
        {
            var session = (UserLogin)Session[WebsiteNoiThat.Common.Commoncontent.user_sesion_admin];
            ViewBag.username = session.Username;

            Category a = db.Categories.SingleOrDefault(n => n.CategoryId == CategoryId);
            return View(a);

        }

        [HttpPost]
        [HasCredential(RoleId = "EDIT_CATE")]
        public ActionResult Edit(Category n)
        {
            if (ModelState.IsValid)
            {
                db.Entry(n).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Show");
            }
            else
            {
                return JavaScript("alert('Error');");
            }
        }


        [HttpPost]
        [HasCredential(RoleId = "DELETE_CATE")]
        public ActionResult Delete(FormCollection formCollection)
        {
            string[] ids = formCollection["CategoryId"].Split(new char[] { ',' });

            foreach (string id in ids)
            {
                var model = db.Categories.Find(Convert.ToInt32(id));
                db.Categories.Remove(model);
                db.SaveChanges();
            }
            return RedirectToAction("Show");
        }

    }
}

WebsiteNoiThat/WebsiteNoiThat/Areas/Admin/Views/ProductCate/Add.cshtml
@model Models.EF.Category

@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Add CategoryProduct</h2>

@using (Html.BeginForm("Add", "ProductCate", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryId, new { htmlAttributes = new { @class = "form-control",@required = "" } })
                @Html.ValidationMessage("CateError")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control",@required = "" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MetaTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MetaTitle, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                @Html.ValidationMessageFor(model => model.MetaTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ParId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ParId, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                @Html.ValidationMessageFor(model => model.ParId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Show")
</div>

WebsiteNoiThat/WebsiteNoiThat/Areas/Admin/Views/ProductCate/Edit.cshtml
@model Models.EF.Category

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit","ProductCate",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CategoryId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MetaTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MetaTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MetaTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ParId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ParId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ParId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Show")
</div>

WebsiteNoiThat/WebsiteNoiThat/Areas/Admin/Views/ProductCate/Show.cshtml
@model IEnumerable<Models.EF.Category>
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<h2>Danh sách loại sản phẩm</h2>
    <p>
        <a href="@Url.Action("Add", "ProductCate")" class="btn btn-primary" style="margin-top:10px;margin-bottom:10px;">Thêm loại sản phẩm</a>
    </p>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
    <div class="card-body">
        <div class="table-responsive">
        <table id="example" class="table table-striped table-bordered table-hover" style="width:100%">
            <thead>
                <tr>
                    <th>Mã loại sản phẩm</th>
                    <th>Tên loại sản phẩm</th>
                    <th>Diễn giải</th>
                    <th>Mã loại SP</th>
                    <th>Hành động</th>
                 
                </tr>
            </thead>

            <tbody>

                @foreach (var item in Model)
                {
                    <tr class="Search">
                        <td> @item.CategoryId</td>
                        <td> @item.Name</td>
                        <td>@item.MetaTitle</td>
                        <td>@item.ParId</td>
                        <td>
                            <input type="button" class="btn btn-sm btn-primary" value="Sửa" onclick="location.href='/Admin/ProductCate/Edit?CategoryId=@item.CategoryId'" /> |
                            <input type="button" class="btn btn-sm btn-danger" value="Xóa" onclick="location.href='/Admin/ProductCate/Delete?CategoryId=@item.CategoryId'" />
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
    

<script src="~/Scripts/jquery-3.3.1.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Content/DataTable/js/jquery.dataTables.min.js"></script>
<script src="~/Content/DataTable/js/dataTables.bootstrap.min.js"></script>

<script type="text/javascript">
    $('#example').DataTable();
</script>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>