WebsiteNoiThat/WebsiteNoiThat/Areas/Admin/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteNoiThat.Areas.Admin.Models;
using Models.DAO;
using WebsiteNoiThat.Common;
using System.Web.Security;

namespace WebsiteNoiThat.Areas.Admin.Controllers
{
    public class LoginController : Controller
    {
        // GET: Admin/Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserDao();
                var result = dao.Login(model.Username, model.Passwword, true);
                if (result == 1)
                {
                    var user = dao.GetById(model.Username);
                    var userSession = new UserLogin();
                    userSession.Username = user.Username;
                    userSession.UserId = user.UserId;
                    Session["UserId"] = user.UserId.ToString();
                    userSession.GroupId = user.GroupId;
                    var listCredentials = dao.GetListCredentials(model.Username);
                    Session.Add(Commoncontent.SESSION_CREDENTIALS, listCredentials);
                    Session.Add(Commoncontent.user_sesion_admin, userSession);
                    return RedirectToAction("Index", "Home");
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tài Khoản không tồn tại!");

                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Tài Khoản đang bị khóa!");
                }
                else if (result == -2)
                {
                    ModelState.AddModelError("", "Mật khẩu không đúng!");
                }
                else if (result == -3)
                {
                    ModelState.AddModelError("", "Tài khoản của bạn không có quyền đăng nhập.");
                }
            }

            return View("Index");
        }
        public ActionResult Logout()
        {
            Session[Commoncontent.user_sesion_admin] = null;
            Session[Commoncontent.SESSION_CREDENTIALS] = null;
           FormsAuthentication.SignOut();
            return RedirectToAction("Index","Login");
        }
         
    }
}

WebsiteNoiThat/WebsiteNoiThat/Controllers/RegisterAndLoginController.cs
using BotDetect.Web.Mvc;
using Models.DAO;
using Models.EF;
using reCAPTCHA.MVC;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteNoiThat.Areas.Admin.Models;
using WebsiteNoiThat.Common;
using WebsiteNoiThat.Models;

namespace WebsiteNoiThat.Controllers
{
    public class RegisterAndLoginController : Controller
    {
        // GET: RegisterAndLogin
        DBNoiThat db = new DBNoiThat();

        public ActionResult Logout()
        {
            Session[Commoncontent.user_sesion] = null;
            Session[Commoncontent.CartSession] = null;
            return Redirect("/");
        }
        
        [HttpGet]
        public ActionResult Login()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult Login(Models.LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserDao();
                //var result = dao.Login(model.UserName, model.Password);
                var result = dao.Login(model.UserName, model.Password);

                if (result == 1)
                {
                    var user = dao.GetById(model.UserName);
                    var userSession = new UserLogin();
                    userSession.Username = user.Username;
                    userSession.UserId = user.UserId;
                    Session.Add(Commoncontent.user_sesion, userSession);
                    return Redirect("/");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Tài Khoản đang bị khóa, liên hệ admin");

                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại");
                }
                else if (result == -2)
                {
                    ModelState.AddModelError("", "Mật khẩu không đúng");
                }
            }
            return View(model);
        }
        [HttpGet]
        
        public ActionResult Register()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Register(RegisterModel model)
        {
            if(ModelState.IsValid)
            {
                var dao = new UserDao();
                if (dao.CheckUserName(model.UserName))
                {
                    ModelState.AddModelError("", "Tên đăng nhập đã tồn tại");
                }
                //else if (dao.CheckEmail(model.Email))
                //{
                //    ModelState.AddModelError("", "Email đã tồn tại");
                //}
                else
                {
                    var user = new User();
                    user.Username = model.UserName;
                    user.Password = model.Password;
                    user.Phone = model.Phone;
                    user.Email = model.Email;
                    user.Address = model.Address;
                    user.Name = model.Name;
                    user.GroupId = "USER";

                    user.Status = true;

                    var result = dao.Insert(user);
                    if (result > 0)
                    {
                        ViewBag.Success = "Đăng ký thành công";
                        var models = db.Users.SingleOrDefault(n => n.Username == model.UserName);
                        return RedirectToAction("Card", new { UserId= models.UserId });
                    }
                    else
                    {
                        ModelState.AddModelError("", "Đăng ký không thành công.");
                    }
                }
            }
            model = new RegisterModel();
            return View();
        }

        [HttpGet]
        public ActionResult ViewCurentUser()
        {
            var session = (UserLogin)Session[WebsiteNoiThat.Common.Commoncontent.user_sesion];
            if (session != null)
            {
                var model = db.Users.SingleOrDefault(n => n.UserId == session.UserId);
                return View(model);
            }
            else
            {
                return Redirect("/RegisterAndLogin/Login");
            }
        }

        [HttpGet]
        public ActionResult EditCurentUser()
        {
            var session = (UserLogin)Session[WebsiteNoiThat.Common.Commoncontent.user_sesion];
            var model = db.Users.SingleOrDefault(n => n.UserId == session.UserId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCurentUser([Bind(Include = "UserId,Name,Address,Phone,Username,Password,Email,GroupId,Status")] User user)
        {
            if (ModelState.IsValid)
            {
                user.Password = user.Password;
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ViewCurentUser");
            }
            return View(user);
        }

        [HttpGet]
        public ActionResult Card(int UserId)

        {
           
            var session = (UserLogin)Session[WebsiteNoiThat.Common.Commoncontent.user_sesion];
            if(session!=null)
            {
                var checkuser = db.Cards.SingleOrDefault(n => n.UserId == session.UserId);
                if (checkuser == null)
                {
                    var m = db.Users.SingleOrDefault(n => n.UserId == UserId);
                    if (m != null)
                    {
                        var model = new Card();
                        model.UserId = session.UserId;
                        model.NumberCard = 0;
                        model.UserNumber = 0;
                        return View(model);

                    }
                    else
                    {
                        //var model = new Card();
                        //model.Username = session.Username;
                        //model.NumberCard = 0;
                        //model.UseNumber = 0;
                        var model = new Card();
                        model.UserId = session.UserId;
                        model.NumberCard = 0;
                        model.UserNumber = 0;
                        
                        return View(model);
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Đã có thẻ tích điểm. Bạn không thể đăng ký thêm.");
                    return View();
                }
            }
            else
            {
                var model = new Card();
                model.UserId = UserId;
                model.NumberCard = 0;
                model.UserNumber = 0;
                return View(model);
            }
           
           
        }
        [HttpPost]
        public ActionResult Card(Card n)
        {
            var model =new Card();
            model.UserId = n.UserId;
            model.NumberCard = 0;
            model.UserNumber = 0;
            model.Identification = n.Identification;

            db.Cards.Add(model);
            db.SaveChanges();
            ViewBag.Success = "Đăng ký thẻ thành công";
            return Redirect("/");
        }
        
        public ActionResult ViewLogin()
        {
            var session = (UserLogin)Session[WebsiteNoiThat.Common.Commoncontent.user_sesion];
           if(session!=null)
            {
                var model = db.Cards.SingleOrDefault(n => n.UserId == session.UserId);
                var models = (from a in db.OrderDetails
                            join b in db.Orders
                            on a.OrderId equals b.OrderId
                            join c in db.Products
                            on a.ProductId equals c.ProductId
                            join d in db.Users on b.UserId equals d.UserId
                            join e in db.Cards on d.UserId equals e.UserId
                            where b.StatusId == 5 && e.UserId == session.UserId
                            select new
                            {
                                ProductId = a.ProductId,
                                Price = a.Price,
                                Quantity = a.Quantity,
                                Discount = c.Discount,
                                NumberCard = e.NumberCard,
                                Username = d.Username
                            }).ToList();
                    if (models.Count()==0)
                    {
                        ViewBag.Card = 0;
                    }
                    else
                    {
                        double? total = 0;
                        foreach (var item in models)
                        {
                            total += ((item.Price.GetValueOrDefault(0) - (item.Price.GetValueOrDefault(0) * item.Discount.GetValueOrDefault(0) * 0.01)) * item.Quantity);
                        }
                      
                        model.NumberCard = Convert.ToInt32(total / 1000)- model.UserNumber;
                        db.SaveChanges();
                        ViewBag.Card = model.NumberCard;
                    }
               
            }
           else
            {
                return PartialView();
            }
            return PartialView();

        }




    }
}

WebsiteNoiThat/WebsiteNoiThat/Views/RegisterAndLogin/Card.cshtml
@model Models.EF.Card
@{
    ViewBag.Title = "Đăng ký thẻ tích điểm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
@using (Html.BeginForm("Card", "RegisterAndLogin", FormMethod.Post))

{
   
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <div class="breadcrumb-wp">
        <ol class="breadcrumb">
            <li><a class="pink" href="#"><i class="fa fa-user-plus"></i></a></li>
            <li class="active">ĐĂNG KÝ THẺ TÍCH ĐIỂM</li>
        </ol>
    </div>
    <hr />
    <a href="/RegisterAndLogin/Login">Bỏ qua đăng ký thẻ tích điểm </a><br />
    <div class="form-group">
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        @if (ViewBag.Success != null)
        {
            <div class="alert alert-success">@ViewBag.Success</div>
        }
    </div>

    <div class="form-group">
        <div class="col-md-offset-1">
            <div class="input-group">
                <h4>Mã khách hàng:<i> @Html.EditorFor(model => model.UserId, new { @class = "form-control ", @required = "" })</i></h4>
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-offset-1">
            <div class="input-group">
                <h4>Chứng minh thư: <i>@Html.EditorFor(model => model.Identification, new { @class = "text-danger", @required = "" })</i></h4>
                @Html.ValidationMessageFor(model => model.Identification, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-1">
            <div class="input-group">
                <h4>Thẻ tích điểm: @Html.ValueFor(model => model.NumberCard)</h4>
                @Html.ValidationMessageFor(model => model.NumberCard, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>






    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Đăng ký" class="btn btn-success" />

        </div>
    </div>
</div>

}

WebsiteNoiThat/WebsiteNoiThat/Views/RegisterAndLogin/EditCurentUser.cshtml
@model Models.EF.User

@{
    ViewBag.Title = "Sửa thông tin tài khoản";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thông tin tài khoản</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.UserId)

    <div class="form-row">
        <div class="form-group col-md-6">
            <label>Tên đăng nhập</label>
            @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-6">
            <label>Mật khẩu</label>
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label>Tên</label>
        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label>Email</label>
        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label>Địa chỉ</label>
        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label>Số điện thoại</label>
        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <div class="checkbox" style="margin-left: 21px;">
            @Html.EditorFor(model => model.Status)
            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
        </div>
        <a style="margin-left: 21px;">Trạng thái kích hoạt</a>
    </div>
    <br />
    <div class="form-group">
        <button type="submit" class="btn btn-warning">Lưu thông tin</button>
        <button class="btn btn-secondary"><a href="/RegisterAndLogin/ViewCurentUser">Huỷ</a></button>
    </div>
}

WebsiteNoiThat/WebsiteNoiThat/Views/RegisterAndLogin/Login.cshtml
@model WebsiteNoiThat.Models.LoginModel

@{
    ViewBag.Title = "Login";
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Đăng nhập | Khách hàng</title>

    <!-- Custom fonts for this template-->
    <link href="~/Content/admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Content/admin/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Xin chào!</h1>
                                    </div>
                                    @using (Html.BeginForm("Login", "RegisterAndLogin", FormMethod.Post))
                                    {
                                        @Html.AntiForgeryToken()
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        <fieldset>
                                            <div class="form-group">
                                                @Html.TextBoxFor(model => model.UserName, new { @class = "form-control form-control-user", @id = "exampleInputEmail", @placeholder = "Tên đăng nhập", @autofocus = "autofocus" })
                                            </div>
                                            <div class="form-group">
                                                @Html.TextBoxFor(model => model.Password, new { @class = "form-control form-control-user", @id = "exampleInputPassword", @placeholder = "Mật khẩu", type = "password" })
                                            </div>
                                            <div class="form-group">
                                                <div class="custom-control custom-checkbox small">
                                                    @*@Html.CheckBoxFor(model => model.rememberme, new { @class = "custom-control-input", @id = "customCheck" })*@

                                                    <label class="custom-control-label" for="customCheck">Remember Me</label>
                                                </div>
                                            </div>
                                            <button type="submit" class="btn btn-primary btn-user btn-block">
                                                Đăng nhập
                                            </button>
                                            <hr>
                                            <a href="#" class="btn btn-google btn-user btn-block">
                                                <i class="fab fa-google fa-fw"></i> Đăng nhập với Google
                                            </a>
                                            <a href="#" class="btn btn-facebook btn-user btn-block">
                                                <i class="fab fa-facebook-f fa-fw"></i> Đăng nhập với Facebook
                                            </a>
                                        </fieldset>
                                    }

                                    <div class="text-center">
                                        <a class="small" href="#">Quên mật khẩu?</a>
                                        <a class="small" href="/RegisterAndLogin/Register">Tạo tài khoản</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="/Admin/Login">Đăng nhập trang quản lý</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Content/admin/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Content/admin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Content/admin/js/sb-admin-2.min.js"></script>

</body>
</html>

WebsiteNoiThat/WebsiteNoiThat/Views/RegisterAndLogin/Register.cshtml
@model WebsiteNoiThat.Models.RegisterModel
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
@using (Html.BeginForm("Register", "RegisterAndLogin", FormMethod.Post))

{

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="breadcrumb-wp">
            <ol class="breadcrumb">
                <li><a class="pink" href="#"><i class="fa fa-user-plus"></i></a></li>
                <li class="active">ĐĂNG KÝ</li>
            </ol>
        </div>
        <hr />
        <div class="form-group">
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
            @if (ViewBag.Success != null)
            {
                <div class="alert alert-success">@ViewBag.Success</div>
            }
        </div>

        <div class="form-group">


            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2 " })
            <div class="col-md-10">
                <div class="input-group">
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-user"></span>
                    </div>
                    @Html.TextBoxFor(model => model.UserName, new { @class = "form-control ", @required = "" })

                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group">
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-lock"></span>
                    </div>
                    @Html.PasswordFor(model => model.Password, new { @class = "form-control", @required = "" })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group">
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-lock"></span>
                    </div>
                    @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control", @required = "" })
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group">
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-user"></span>
                    </div>
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @required = "" })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group">
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-globe"></span>
                    </div>
                    @Html.TextAreaFor(model => model.Address, new { @class = "form-control", @required = "" })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group">
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-envelope"></span>
                    </div>
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @required = "" })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group">
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-phone"></span>
                    </div>
                    @Html.TextBoxFor(model => model.Phone, new { @class = "form-control", @required = "" })
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-3">

                @*@Html.Captcha(registerCaptcha)
                    @Html.TextBox("CaptchaCode")*@
                @*@Html.Recaptcha()
                @Html.ValidationMessage("ReCaptcha")*@

            </div>
        </div>




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Đăng ký" class="btn btn-success" />
            </div>
        </div>
    </div>

}
@*<div style="text-align:center">
    <a href="/RegisterAndLogin/Login"> <input type="submit" value="Đăng nhập" class="btn btn-info" /></a>
</div>*@

WebsiteNoiThat/WebsiteNoiThat/Views/RegisterAndLogin/ViewCurentUser.cshtml
@model Models.EF.User

@{
    ViewBag.Title = "Xem thông tin tài khoản";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thông tin tài khoản</h2>
<div>
    <fieldset disabled>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="username">Tên đăng nhập</label>
                <input type="text" class="form-control" id="username" placeholder=@Model.Username>
            </div>
            <div class="form-group col-md-6">
                <label for="password">Mật khẩu</label>
                <input type="password" class="form-control" id="password" placeholder=@Model.Password>
            </div>
        </div>
        <div class="form-group">
            <label for="inputAddress">Tên</label>
            <input type="text" class="form-control" id="name" placeholder=@Model.Name>
        </div>
        <div class="form-group">
            <label for="inputAddress">Email</label>
            <input type="text" class="form-control" id="email" placeholder=@Model.Email>
        </div>
        <div class="form-group">
            <label for="address">Địa chỉ</label>
            <input type="text" class="form-control" id="address" placeholder=@Model.Address>
        </div>
        <div class="form-group">
            <label for="phone">Số điện thoại</label>
            <input type="text" class="form-control" id="phone" placeholder=@Model.Phone>
        </div>

        <div class="form-group">
            <div class="form-check">
                @{
                    if (Model.Status)
                    {
                        <input class="form-check-input" type="checkbox" id="status" checked style="margin-left: -11px;">

                    }
                    else
                    {
                        <input class="form-check-input" type="checkbox" id="status" style="margin-left: -11px;">

                    }
                }
            </div>
            <a style="margin-left: 21px;">Trạng thái kích hoạt</a>
        </div>
        <fieldset disabled>
            <button class="btn btn-warning"> <a href="/RegisterAndLogin/EditCurentUser">Sửa thông tin</a></button>
</div>

WebsiteNoiThat/WebsiteNoiThat/Views/RegisterAndLogin/ViewLogin.cshtml
@{
    var session = (UserLogin)Session[WebsiteNoiThat.Common.Commoncontent.user_sesion];
}

@if (session != null)
{
    <a id="a_account" href="/RegisterAndLogin/ViewCurentUser"><img src="~/Content/client/assets/img/round-account-button-with-user-inside.png" /></a>
    <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown">
        @session.Username
    </button>
    <ul class="dropdown-menu dropdown-user" id="account_dropdown">

        <li>
            <a href="/Cart/HistoryCart"><i class="fa fa-hourglass"></i> Lịch sử mua hàng</a>
        </li>
        <li>
            <a href=""><i class="fa fa-credit-card"></i> Thẻ tích điểm:@ViewBag.Card </a>
        </li>

        <li>
            <a href="@Url.Action("Card", "RegisterAndLogin", new { @UserId=session.UserId })"><i class="fa fa-sign-in"></i> Đăng ký thẻ tích điểm</a>
        </li>
        <li>
            <a href="/RegisterAndLogin/Logout"><i class="fa fa-sign-out"></i> Đăng xuất</a>
        </li>

    </ul>
}
else
{
    <a id="a_account" href="/RegisterAndLogin/Login"><img src="~/Content/client/assets/img/round-account-button-with-user-inside.png" /></a>
}